# Generated by Django 3.1.6 on 2021-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyphrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=40)),
                ('wiki_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('wiki_url', models.URLField(blank=True, null=True)),
                ('wiki_dis', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('uploader', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('keyphrases', models.ManyToManyField(to='api.Keyphrases')),
            ],
        ),
    ]
