# Generated by Django 3.1.6 on 2021-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdoc',
            name='uploader',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
