# Generated by Django 3.1.6 on 2021-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210204_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyphrases',
            name='wiki_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='textdoc',
            name='uploader',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
